### ISSUE TITLE
Add certbot command

### ISSUE THREAD

**Issue by pydanny** [GrahamDumpleton/warpdrive#1]
Let's Encrypt is a thing.

**Comment by GrahamDumpleton** [comment]
Implementation of lets-encrypt is something that really sits separate to what warpdrive does. How you handle lets-encrypt also depends on how you are hosting something anyway. In the case of containers, which warpdrive is mainly targeting, TLS termination is handled in an separate routing layer, so need to handle it there. So closing for now as don't see how can incorporate at this layer.
